/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample.gradle.multi.app;

import sample.gradle.multi.list.LinkedList;

import static sample.gradle.multi.utilities.StringUtils.join;
import static sample.gradle.multi.utilities.StringUtils.split;
import static sample.gradle.multi.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
