/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample.gradle.multi.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
